export const PRODUCT = {
  DOCUMENT_NAME: 'Product',
  DOCUMENT_CLOTHING_NAME: 'Clothing',
  DOCUMENT_ELECTRON_NAME: 'Electronic',
  DOCUMENT_FURNITURE_NAME: 'Furniture',
  COLLECTION_NAME: 'Products',
  COLLECTION_CLOTHING_NAME: 'Clothings',
  COLLECTION_ELECTRON_NAME: 'Electronics',
  COLLECTION_FURNITURE_NAME: 'Furnitures',
};
